# Adds documentation generation to your GitHub Actions workflow.
name: Swift
on: 
  push:
    paths:
      Sources/**
      .github/workflows/documentation.yml
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  create-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: fwcd/swift-docc-action@v1
        with:
          target: YourTarget
          output: ./docs
          hosting-base-path: yourproject
          disable-indexing: 'true'
          transform-for-static-hosting: 'true'